services:
  - type: web
    name: smiling-steps-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://KennethEsilo:9213@cluster0.m7v7wpi.mongodb.net/smiling-steps?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_USER
        value: kennethes251@gmail.com
      - key: EMAIL_PASSWORD
        value: gmhp uzew qwpl zepz
      - key: FROM_EMAIL
        value: hr@smilingsteps.com
      - key: FROM_NAME
        value: Smiling Steps
      - key: CLIENT_URL
        value: https://smiling-steps-frontend.onrender.com

  - type: web
    name: smiling-steps-frontend
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://smiling-steps-backend.onrender.com
